cmake_minimum_required(VERSION 3.20)
project(mlir_clamp_exercise LANGUAGES C CXX)
find_package(MLIR REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
include(TableGen)
include(AddLLVM)
include(AddMLIR)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(SYSTEM ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../05-op-definition
                    ${CMAKE_CURRENT_BINARY_DIR}/reference)
add_definitions(${LLVM_DEFINITIONS})
if(NOT LLVM_ENABLE_RTTI)
  add_compile_options(-fno-rtti)
endif()
add_subdirectory(../../05-op-definition reference EXCLUDE_FROM_ALL)
add_executable(student-opt student-opt.cpp Exercise.cpp)
target_link_libraries(student-opt PRIVATE LabOps MLIROptLib MLIRFuncDialect
  MLIRArithDialect MLIRPass MLIRTransforms MLIRRewrite)
