cmake_minimum_required(VERSION 3.20)
project(mlir_ir_definition LANGUAGES C CXX)
find_package(MLIR REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
include(TableGen)
include(AddLLVM)
include(AddMLIR)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(SYSTEM ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
  ${CMAKE_CURRENT_SOURCE_DIR}/../05-op-definition ${CMAKE_CURRENT_BINARY_DIR}/basic)
add_definitions(${LLVM_DEFINITIONS})
if(NOT LLVM_ENABLE_RTTI)
 add_compile_options(-fno-rtti)
endif()
add_subdirectory(../05-op-definition basic EXCLUDE_FROM_ALL)
set(LLVM_TARGET_DEFINITIONS Lesson.td)
mlir_tablegen(LessonDialect.h.inc -gen-dialect-decls -dialect=lesson)
mlir_tablegen(LessonDialect.cpp.inc -gen-dialect-defs -dialect=lesson)
mlir_tablegen(LessonTypes.h.inc -gen-typedef-decls -typedefs-dialect=lesson)
mlir_tablegen(LessonTypes.cpp.inc -gen-typedef-defs -typedefs-dialect=lesson)
mlir_tablegen(LessonAttrs.h.inc -gen-attrdef-decls -attrdefs-dialect=lesson)
mlir_tablegen(LessonAttrs.cpp.inc -gen-attrdef-defs -attrdefs-dialect=lesson)
mlir_tablegen(LessonInterfaces.h.inc -gen-op-interface-decls)
mlir_tablegen(LessonInterfaces.cpp.inc -gen-op-interface-defs)
mlir_tablegen(LessonOps.h.inc -gen-op-decls)
mlir_tablegen(LessonOps.cpp.inc -gen-op-defs)
add_public_tablegen_target(LessonIncGen)
add_library(Lesson STATIC Lesson.cpp)
add_dependencies(Lesson LessonIncGen)
target_link_libraries(Lesson PUBLIC MLIRIR MLIRSideEffectInterfaces)
foreach(tool lesson-opt lesson-opt-no-model)
 add_executable(${tool} lesson-opt.cpp)
 target_link_libraries(${tool} PRIVATE Lesson LabOps MLIROptLib MLIRFuncDialect MLIRArithDialect MLIRPass MLIRTransforms)
endforeach()
target_compile_definitions(lesson-opt-no-model PRIVATE OMIT_MODEL)
add_executable(type-probe type-probe.cpp)
target_link_libraries(type-probe PRIVATE Lesson)
