cmake_minimum_required(VERSION 3.20)
project(mlir_op_definition LANGUAGES C CXX)
find_package(MLIR REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
include(TableGen)
include(AddLLVM)
include(AddMLIR)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(SYSTEM ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR})
add_definitions(${LLVM_DEFINITIONS})
if(NOT LLVM_ENABLE_RTTI)
  add_compile_options(-fno-rtti)
endif()
# BEGIN: tablegen
set(LLVM_TARGET_DEFINITIONS LabOps.td)
mlir_tablegen(LabOps.h.inc -gen-op-decls)
mlir_tablegen(LabOps.cpp.inc -gen-op-defs)
mlir_tablegen(LabDialect.h.inc -gen-dialect-decls -dialect=lab)
mlir_tablegen(LabDialect.cpp.inc -gen-dialect-defs -dialect=lab)
add_public_tablegen_target(LabOpsIncGen)
# END: tablegen
add_library(LabOps STATIC LabOps.cpp)
add_dependencies(LabOps LabOpsIncGen)
target_link_libraries(LabOps PUBLIC MLIRIR MLIRSideEffectInterfaces)
add_executable(lab-dialect-opt lab-dialect-opt.cpp ExpandClamp.cpp)
target_link_libraries(lab-dialect-opt PRIVATE LabOps MLIROptLib MLIRFuncDialect
  MLIRArithDialect MLIRPass MLIRTransforms MLIRRewrite)
add_executable(lab-build lab-build.cpp)
target_link_libraries(lab-build PRIVATE LabOps MLIRFuncDialect)
