cmake_minimum_required(VERSION 3.20)
project(mlir_small_pass LANGUAGES C CXX)
find_package(MLIR REQUIRED CONFIG)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(lab-opt lab-opt.cpp LabPass.cpp)
target_include_directories(lab-opt SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
add_definitions(${LLVM_DEFINITIONS})
if(NOT LLVM_ENABLE_RTTI)
  target_compile_options(lab-opt PRIVATE -fno-rtti)
endif()
target_link_libraries(lab-opt PRIVATE MLIROptLib MLIRPass MLIRArithDialect
  MLIRFuncDialect MLIRSCFDialect MLIRTransforms MLIRRewrite MLIRIR MLIRSupport)
